name: ci

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  validate-renovate-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bunx -p renovate renovate-config-validator --strict
